# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Techrangers
email: techranges@ucf.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Techrangers® is a team of students at the Center for Distributed Learning,
  who provide course development for faculty and web/application development for
  the University of Central Florida (UCF).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techrangers.cdl.ucf.edu" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-36116523-10

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: techrangers_current
    values:
      layout: profile
  - scope:
      path: ""
      type: techrangers_past
    values:
      layout: profile

collections:
  techrangers_current:
    output: true
  techrangers_past:
    output: true

permalink: /:year/:month/:day/:title:output_ext

# allow posts/items dated in the future to show up on the site
future: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - RAKEFILE
  - Gemfile
  - Gemfile.lock
  - README.MD
  - dockerfile
  - vendor
