name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler: "2.2.4"

      - name: Install Dependencies
        run: |
          bundle install --path=vendor/

      - name: Build Jekyll
        run: bundle exec jekyll build

      - name: List site contents
        run: ls _site/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync S3 bucket
        run: aws s3 sync ./_site/ s3://${{ vars.TARGET_BUCKET }}/ --acl public-read --delete --cache-control max-age=86400

      - name: Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation --paths '/*'  --distribution-id ${{ vars.CLOUDFRONT_DISTRO_ID }}
          aws cloudfront list-invalidations --distribution-id ${{ vars.CLOUDFRONT_DISTRO_ID }}
