name: Build

on: push

env:
  BUILD_ARTIFACT: build

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --path=vendor/
      - name: Build Jekyll
        run: bundle exec jekyll build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: _site/
      - name: List site contents
        run: |
          cd _site/
          ls
